# Generated by Django 2.2 on 2019-05-09 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190508_0927'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substitution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userfavorite', to='products.Product')),
                ('to_substitute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userfavorite_related', to='products.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
