# Generated by Django 2.2 on 2019-05-09 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190509_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorite',
            name='to_substitute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userfavorite_tosubstitute', to='products.Product'),
        ),
    ]
